name: hep-th daily forecast bot

on:
  schedule:
    - cron: "0 17 * * 0-4"   # 17:00 UTC, Sunday–Thursday
  workflow_dispatch:         # allow manual runs too

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          DATA_DIR: data
          MODEL_PATH: GBTmodel.pkl
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          # DRY_RUN: "1"  # uncomment to test without posting
        run: python bot.py